version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
      - image: circleci/mysql:5.6.39
    environment:
      db_name: "circle_test"
      db_user: "root"
      db_password: ""
      db_host: "localhost"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    machine: true
    steps:
      - checkout
      - run: ssh ec2-user@ec2-13-56-156-13.us-west-1.compute.amazonaws.com "cd eco-chamber && git reset --hard && git fetch origin && git checkout master && git reset --hard origin/master && npm install && node_modules/.bin/webpack && pm2 restart server"
workflows:
  version: 2
  test-only:
    jobs:
      - test
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
