version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
      - image: circleci/mysql:5.6.39
    environment:
      db_name: "ecotest"
      db_user: "root"
      db_password: ""
      db_host: "localhost"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install mysql-server
      = run: sudo service mysql start
      - run: npm install
      - run: mysql -u root -e "create database ecotest"
      - run: npm test
  deploy:
    machine: true
    steps:
      - checkout
      - run: ssh ec2-user@ec2-13-56-156-13.us-west-1.compute.amazonaws.com "cd eco-chamber && git reset --hard && git fetch origin && git checkout master && git reset --hard origin/master && npm install && node_modules/.bin/webpack && pm2 restart server"
workflows:
  version: 2
  test-only:
    jobs:
      - test
  test-and-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
