version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    machine: true
    steps:
      - checkout
      - run: ssh ec2-user@ec2-13-56-156-13.us-west-1.compute.amazonaws.com "cd eco-chamber && git fetch origin && git checkout develop && git reset --hard origin/develop && npm install && node_modules/.bin/webpack && pm2 restart server"
workflows:
  version: 2
  test-only:
    jobs:
      - test
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: develop
